version: '3.8'

services:
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=myuser
      - POSTGRES_PASSWORD=mypassword
      - POSTGRES_DB=median-db
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - 8888:5432

volumes:
  postgres:
